image: docker:stable

services:
  - docker:stable-dind

stages:
  - package
  - build
  - review
  - deploy-stage
  #- integration-test
  - deploy-prod
  - tag

package:
  image: maven:3.8.2-jdk-11-slim
  stage: package
  script:
    - VERSION=`mvn -B org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -Ev '(^\[|Download\w+:)' | sed 's/\([0-9]*\.[0-9]*\.[0-9]*\)-SNAPSHOT/\1/g'`
    - echo $VERSION
    - echo "VERSION=$VERSION" > version
    - mvn --no-transfer-progress --batch-mode clean package -DskipTests
  artifacts:
    untracked: true
    expire_in: 1 days

build:
  image: kiwigrid/gcloud-kubectl-helm
  stage: build
  script:
    - source version
    - echo "$GCP_SERVICE_KEY" > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud config set project focal-appliance-323806
    - export DATE=$(date +%Y%m%d%H%M%S)
    - gcloud builds submit -t eu.gcr.io/focal-appliance-323806/ca-challenge:$VERSION-$DATE .
    - echo "VERSION=$VERSION-$DATE" > variables
  artifacts:
    paths:
      - variables

start-review:
  image: kiwigrid/gcloud-kubectl-helm
  stage: review
  dependencies:
    - build
  before_script:
    - |
      echo "$GCP_SERVICE_KEY" > key.json
      gcloud auth activate-service-account --key-file key.json
      gcloud config set project focal-appliance-323806
      gcloud container clusters get-credentials poc-cluster --region europe-west3
  script:
    - source variables
    - cd ./k8s
    - |
      helm upgrade --install \
      --wait \
      --timeout 600 \
      --set image="eu.gcr.io/focal-appliance-323806/ca-challenge:$VERSION" \
      --set BASEURL="app-$CI_ENVIRONMENT_SLUG.review.barunavodev.de" \
      --set MYSQL_HOST="mysql-deployment.mysql.svc.cluster.local" \
      --set MYSQL_USER="root" \
      --set MYSQL_PASSWORD="$MYSQL_PASSWORD" \
      --set APP_VERSION="review" \
      --namespace="review" \
      --values ./java-deployment/values-dev.yaml \
      "app-$CI_COMMIT_REF_SLUG" \
      java-deployment/
  environment:
    name: review/$CI_COMMIT_REF_NAME
    on_stop: stop-review
  except:
    - master
  only:
    - branches

stop-review:
  image: kiwigrid/gcloud-kubectl-helm
  stage: review
  variables:
    GIT_STRATEGY: none
  before_script:
    - |
      echo "$GCP_SERVICE_KEY" > key.json
      gcloud auth activate-service-account --key-file key.json
      gcloud config set project focal-appliance-323806
      gcloud container clusters get-credentials poc-cluster --region europe-west3
  script:
    - helm delete "app-$CI_COMMIT_REF_SLUG" --namespace="review"
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  except:
    - master
  only:
    - branches

deploy-qa:
  image: kiwigrid/gcloud-kubectl-helm
  stage: deploy-stage
  dependencies:
    - build
  before_script:
    - |
      echo "$GCP_SERVICE_KEY" > key.json
      gcloud auth activate-service-account --key-file key.json
      gcloud config set project focal-appliance-323806
      gcloud container clusters get-credentials poc-cluster --region europe-west3
  script:
    - source variables
    - cd ./k8s
    - |
      helm upgrade --install \
      --wait \
      --timeout 600 \
      --set image="eu.gcr.io/focal-appliance-323806/ca-challenge:$VERSION" \
      --set BASEURL="app.stage.barunavodev.de" \
      --set MYSQL_HOST="mysql-deployment.mysql.svc.cluster.local" \
      --set MYSQL_USER="root" \
      --set MYSQL_PASSWORD="$MYSQL_PASSWORD" \
      --set APP_VERSION="stage" \
      --set ENVIRONMENT="stage" \
      --values ./java-deployment/values-stage.yaml \
      --namespace="stage" \
      "app-stage" \
      java-deployment/
  environment:
    name: stage
    url: http://app.stage.barunavodev.de/
  only:
    - master
  allow_failure: false
  when: manual

# integration-tests:
#   variables:
#     TESTS_PROJECT_ID: 2549
#   image: registry.gitlab.com/finestructure/pipeline-trigger
#   stage: integration-test
#   script:
#     - trigger -h https://gitlab.qintern.de -u /api/v4/projects -v false -a "$GITLAB_PIPELINE_USER_ACCESS_TOKEN" -p "$TESTS_PROJECT_PIPELINE_TRIGGER_TOKEN" -t master "$TESTS_PROJECT_ID"
#   only:
#     - master
#   when: manual
#   allow_failure: true

deploy-prod:
  image: kiwigrid/gcloud-kubectl-helm
  stage: deploy-prod
  dependencies:
    - build
  before_script:
    - echo "$GCP_SERVICE_KEY" > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud config set project focal-appliance-323806
    - gcloud container clusters get-credentials poc-cluster --region europe-west3
  script:
    - source variables
    - cd ./k8s
    - |
      helm upgrade --install \
      --wait \
      --timeout 600 \
      --set image="eu.gcr.io/focal-appliance-323806/ca-challenge:$VERSION" \
      --set BASEURL="app.prod.barunavodev.de" \
      --set MYSQL_HOST="mysql-deployment.mysql.svc.cluster.local" \
      --set MYSQL_USER="root" \
      --set MYSQL_PASSWORD="$MYSQL_PASSWORD" \
      --set APP_VERSION="prod" \
      --set ENVIRONMENT="prod" \
      --set REPLICAS="2" \
      --values ./java-deployment/values-prod.yaml \
      --namespace="prod" \
      "app-prod" \
      java-deployment/
  environment:
    name: Prod
    url: https://app.prod.barunavodev.de/
  only:
    - master
  when: manual

tag:
  image: maven:3.8.2-jdk-11-slim
  stage: tag
  before_script:
    - apt-get update && apt-get install git -y
    - git config --global user.email "username@domain.com"
    - git config --global user.name "username"
  script:
    - git checkout -B "$CI_BUILD_REF_NAME" "$CI_BUILD_REF"
    - mvn --batch-mode --no-transfer-progress release:prepare release:perform
  only:
    - master
  when: manual
