values-external-platform.yaml
controller:
  replicaCount: 3
  ingressClass: "nginx-ext"
  config:
    enable-vts-status: "false"
    ssl-ciphers: "ECDHE-RSA-AES128-GCM-SHA256::ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256"
    ssl-protocols: "TLSv1.2"
    log-format-escape-json: "true"
    log-format-upstream: '{ "@timestamp": "$time_iso8601", "remote_addr":
        "$remote_addr", "x-forward-for": "$proxy_add_x_forwarded_for",
        "request_id": "$req_id", "remote_user": "$remote_user", "bytes_sent":
        $bytes_sent, "request_time": $request_time, "status": "$status",
        "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri",
        "request_query": "$args", "request_length": $request_length,
        "method": "$request_method", "http_referrer":
        "$http_referer", "http_user_agent": "$http_user_agent",
        "service_port": "$service_port" }'
  service:
    externalTrafficPolicy: "Local"
  podLabels:
    service: prod-ext
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: service
            operator: In
            values:
            - prod-ext
        topologyKey: kubernetes.io/hostname
